---
# https://github.com/LukeFlynn/ansible
# This playbook is used to configure various services within my private infrastructure.

- name: Common Configuration
  hosts: all
  remote_user: deploy
  roles:
    - common

- name: NGINX Configuration
  hosts: nginx
  remote_user: deploy
  roles: 
    - nginx

- name: MariaDB Configuration
  hosts: mariadb
  remote_user: deploy
  roles:
    - nginx



