---
# Install FreeIPA-Server package.. perhaps I'll make this more automated soonish?

- name: Install ipa-server
  package: name="{{ item }}" state=installed
  with_items:
    - epel-release
    - ipa-server
    - ipa-server-dns
    - bind-dyndb-ldap
