---
# Common tasks for hosts within my private infrastructure. 

- name: Fetch and apply updates
  package: name=* state=latest
  
  - name: Install common packages
  package: name="{{ item }}" state=installed
  with_items:
    - epel-release
    - tmux
    - vim
    - vim-enhanced
    - htop
    - ipa-client 
    - libselinux-python
    - libsemanage-python
    - policycoreutils-python
    - bash-completion

- name: Install Open-VM-Tools on VMWare based machines.
  package: name=open-vm-tools state=installed
  when: ansible_virtualization_type == "VMware"

- name: Add SSH key to local "deploy" user
  authorized_key: user=luke key="{{ item }}"
  with_items: 
    # Luke H. Flynn
    - https://raw.githubusercontent.com/LukeFlynn/dotfiles/master/ssh/id_rsa.pub  
- name: Disable password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  
- name: Reboot all machines
  shell: sleep 2 && shutdown -r now "Reboot triggered by Ansible.. applying updates"
  async: 1
  poll: 0
  ignore_errors: true

- name: Waiting for reboot to complete
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
